# Binary Logistic Regression

We perform a Logistic Regression when we have a set of features $x$ we want to map to some label $y$, but we can't (or don't want to) explicitly find a solution.

A Binary Logistic Regression takes as input a training set $(X,Y)$, where $ X \in \mathbb{R}^{n_x, m}$, i.e. a $m$ column vectors, called **examples**, with $n_x$ entries, called **features**.

The Cost Function, denoted by $J(\omega, b)$, is defined as
$$J(\omega, b) = \frac{1}{m}\sum_{i=1}^m L(A^{(i)}, Y^{(i)}),$$ where
$L(A, Y)$ is the Loss Function (error of single training
example), defined as $$L(A, Y) = -\Big[Y*\ln(A) + (1-Y)*\ln(1-A)\Big]$$

In [4]:
import numpy as np

from bokeh.plotting import figure
from bokeh.io import show, output_notebook, reset_output
reset_output()
output_notebook()
range = 7
p = figure(x_axis_label='x', y_axis_label='sigmoid(x)')
p.line(np.linspace(0.01, 1, num=1000), -np.log(np.linspace(0.01, 1, num=1000)))
show(p)

Loading BokehJS ...

In [18]:
a = np.array([[1,2,3],[3,2,1]]).T
diag = np.array([2,4,6])
d = np.diag(diag)

In [19]:
print(a)
print(d)

[[1 3]
 [2 2]
 [3 1]]
[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [20]:
np.dot(d,a)

array([[ 2,  6],
       [ 8,  8],
       [18,  6]])

In [21]:
! pip install planar

    100% |████████████████████████████████| 563kB 1.6MB/s ta 0:00:01
  Running setup.py bdist_wheel for planar ... done
  Stored in directory: /Users/brunomurino/Library/Caches/pip/wheels/31/5b/24/37a87d0847c2fa5447a36416c3cad23c1826fd992d99a088ca
Successfully built planar


In [25]:
import planar
from planar_utils import plot_decision_boundary, sigmoid, load_planar_dataset, load_extra_datasets

ModuleNotFoundError: No module named 'planar_utils'